import {
  CUSTOM_SHADER_ENTRY_EXPORT,
  CUSTOM_SHADER_INTERNAL_VISIBILITY,
  CUSTOM_SHADER_STARTER,
} from "@/lib/editor/custom-shader/shared"
import { TEXT_FONT_OPTIONS } from "@/lib/editor/text-fonts"
import type {
  EffectLayerType,
  LayerDefinition,
  LayerKind,
  LayerType,
  ModelLayerType,
  ParameterDefinitions,
  SourceLayerType,
} from "@/types/editor"

const mediaPlacementParams = [
  {
    defaultValue: "cover",
    key: "fitMode",
    label: "填充方式",
    options: [
      { label: "覆盖", value: "cover" },
      { label: "包含", value: "contain" },
    ],
    type: "select",
  },
  {
    defaultValue: 1,
    key: "scale",
    label: "缩放",
    max: 4,
    min: 0.25,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: [0, 0] as [number, number],
    key: "offset",
    label: "偏移",
    max: 1,
    min: -1,
    step: 0.01,
    type: "vec2",
  },
] as const satisfies ParameterDefinitions

const imageParams = [
  ...mediaPlacementParams,
  {
    defaultValue: "2048",
    key: "svgRasterResolution",
    label: "栅格化分辨率",
    options: [
      { label: "1024", value: "1024" },
      { label: "2048", value: "2048" },
      { label: "4096", value: "4096" },
      { label: "8192", value: "8192" },
    ],
    type: "select",
  },
] as const satisfies ParameterDefinitions

const videoParams = [
  ...mediaPlacementParams,
  {
    defaultValue: 1,
    key: "playbackRate",
    label: "播放速率",
    max: 4,
    min: 0.25,
    step: 0.05,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const liveParams = [
  {
    defaultValue: "user",
    key: "facingMode",
    label: "摄像头",
    options: [
      { label: "前置", value: "user" },
      { label: "后置", value: "environment" },
    ],
    type: "select",
  },
  {
    defaultValue: true,
    key: "mirror",
    label: "镜像",
    type: "boolean",
  },
  {
    defaultValue: "cover",
    key: "fitMode",
    label: "填充方式",
    options: [
      { label: "覆盖", value: "cover" },
      { label: "包含", value: "contain" },
    ],
    type: "select",
  },
  {
    defaultValue: 1,
    key: "scale",
    label: "缩放",
    max: 4,
    min: 0.25,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: [0, 0] as [number, number],
    key: "offset",
    label: "偏移",
    max: 1,
    min: -1,
    step: 0.01,
    type: "vec2",
  },
] as const satisfies ParameterDefinitions

const customShaderParams = [
  {
    animatable: false,
    defaultValue: false,
    key: "effectMode",
    label: "特效模式",
    type: "boolean",
    visibleWhen: CUSTOM_SHADER_INTERNAL_VISIBILITY,
  },
  {
    animatable: false,
    defaultValue: "paste",
    key: "sourceMode",
    label: "源模式",
    options: [
      { label: "粘贴", value: "paste" },
      { label: "文件", value: "file" },
    ],
    type: "select",
    visibleWhen: CUSTOM_SHADER_INTERNAL_VISIBILITY,
  },
  {
    animatable: false,
    defaultValue: CUSTOM_SHADER_STARTER,
    key: "sourceCode",
    label: "源代码",
    type: "text",
    visibleWhen: CUSTOM_SHADER_INTERNAL_VISIBILITY,
  },
  {
    animatable: false,
    defaultValue: "",
    key: "sourceFileName",
    label: "源文件",
    type: "text",
    visibleWhen: CUSTOM_SHADER_INTERNAL_VISIBILITY,
  },
  {
    animatable: false,
    defaultValue: CUSTOM_SHADER_ENTRY_EXPORT,
    key: "entryExport",
    label: "入口导出",
    maxLength: 64,
    type: "text",
    visibleWhen: CUSTOM_SHADER_INTERNAL_VISIBILITY,
  },
  {
    animatable: false,
    defaultValue: 0,
    key: "sourceRevision",
    label: "源版本",
    max: Number.MAX_SAFE_INTEGER,
    min: 0,
    step: 1,
    type: "number",
    visibleWhen: CUSTOM_SHADER_INTERNAL_VISIBILITY,
  },
] as const satisfies ParameterDefinitions

const textParams = [
  {
    defaultValue: "SuperOPC",
    key: "text",
    label: "文本",
    maxLength: 32,
    type: "text",
  },
  {
    animatable: false,
    defaultValue: "center",
    group: "位置",
    key: "anchor",
    label: "锚点",
    options: [
      { label: "左上", value: "top-left" },
      { label: "上中", value: "top-center" },
      { label: "右上", value: "top-right" },
      { label: "左中", value: "center-left" },
      { label: "居中", value: "center" },
      { label: "右中", value: "center-right" },
      { label: "左下", value: "bottom-left" },
      { label: "下中", value: "bottom-center" },
      { label: "右下", value: "bottom-right" },
    ],
    type: "select",
    ui: "anchor-grid",
  },
  {
    defaultValue: [0, 0] as [number, number],
    group: "位置",
    key: "offset",
    label: "偏移",
    max: 1,
    min: -1,
    step: 0.01,
    type: "vec2",
  },
  {
    defaultValue: 48,
    key: "fontSize",
    label: "字号",
    max: 600,
    min: 48,
    step: 1,
    type: "number",
  },
  {
    defaultValue: "sans",
    key: "fontFamily",
<<<<<<< HEAD
    label: "字体",
    options: [
      { label: "衬线展示体", value: "display-serif" },
      { label: "等宽", value: "mono" },
      { label: "无衬线", value: "sans" },
      { label: "Impact", value: "impact" },
    ],
=======
    label: "字体",
    options: TEXT_FONT_OPTIONS,
>>>>>>> upstream/main
    type: "select",
  },
  {
    defaultValue: 700,
    key: "fontWeight",
    label: "字重",
    max: 900,
    min: 100,
    step: 1,
    type: "number",
  },
  {
    defaultValue: -0.05,
    key: "letterSpacing",
    label: "字间距",
    max: 0.3,
    min: -0.2,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "#ffffff",
    key: "textColor",
    label: "文字颜色",
    type: "color",
  },
  {
    defaultValue: "#000000",
    key: "backgroundColor",
    label: "背景",
    type: "color",
  },
  {
    defaultValue: 1,
    key: "backgroundAlpha",
    label: "背景透明度",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const inkParams = [
  {
    defaultValue: 13,
    group: "墨水渗色",
    key: "blurPasses",
    label: "拖尾次数",
    max: 20,
    min: 1,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 3,
    group: "墨水渗色",
    key: "crispPasses",
    label: "锐化次数",
    max: 6,
    min: 1,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 0.81,
    group: "墨水渗色",
    key: "crispBlend",
<<<<<<< HEAD
    label: "文字清晰度",
=======
    label: "细节混合",
>>>>>>> upstream/main
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.044,
    group: "墨水渗色",
    key: "blurStrength",
    label: "渗色强度",
    max: 0.08,
    min: 0.001,
    step: 0.001,
    type: "number",
  },
  {
    defaultValue: 90,
    group: "墨水渗色",
    key: "blurDirection",
    label: "流向",
    max: 180,
    min: -180,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "墨水渗色",
    key: "dripLength",
    label: "滴落长度",
    max: 10,
    min: 1,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: 0.4,
    group: "墨水渗色",
    key: "dripWeight",
    label: "滴落权重",
    max: 2,
    min: 0.2,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: 0.02,
    group: "墨水渗色",
    key: "fluidNoise",
    label: "流体噪点",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.2,
    group: "墨水渗色",
    key: "noiseScale",
    label: "噪点缩放",
    max: 8,
    min: 0.5,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: 0.36,
    group: "墨水渗色",
    key: "smokeSpeed",
    label: "烟雾速度",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    group: "墨水渗色",
    key: "smokeTurbulence",
    label: "烟雾湍流",
    max: 1.5,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.6,
    group: "墨水渗色",
    key: "blurSpread",
    label: "扩散",
    max: 4,
    min: 0.5,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: "gradient",
    group: "颜色",
    key: "colorMode",
    label: "颜色模式",
    options: [
      { label: "渐变", value: "gradient" },
      { label: "源", value: "source" },
    ],
    type: "select",
  },
  {
    defaultValue: "#fffde8",
    group: "发光颜色",
    key: "coreColor",
    label: "核心色",
    type: "color",
    visibleWhen: {
      equals: "gradient",
      key: "colorMode",
    },
  },
  {
    defaultValue: "#FFA700",
    group: "发光颜色",
    key: "midColor",
    label: "中间色",
    type: "color",
    visibleWhen: {
      equals: "gradient",
      key: "colorMode",
    },
  },
  {
    defaultValue: "#7192F1",
    group: "发光颜色",
    key: "edgeColor",
    label: "边缘色",
    type: "color",
    visibleWhen: {
      equals: "gradient",
      key: "colorMode",
    },
  },
  {
    defaultValue: "#000000",
    group: "颜色",
    key: "backgroundColor",
    label: "背景",
    type: "color",
  },
  {
    defaultValue: false,
    group: "颗粒",
    key: "grainEnabled",
    label: "启用颗粒",
    type: "boolean",
  },
  {
    defaultValue: 0.3,
    group: "颗粒",
    key: "grainIntensity",
    label: "颗粒强度",
    max: 0.3,
    min: 0,
    step: 0.005,
    type: "number",
  },
  {
    defaultValue: 1.5,
    group: "颗粒",
    key: "grainScale",
    label: "颗粒缩放",
    max: 5,
    min: 0.5,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: true,
    group: "泛光",
    key: "bloomEnabled",
    label: "泛光",
    type: "boolean",
  },
  {
    defaultValue: 6.19,
    group: "泛光",
    key: "bloomIntensity",
    label: "强度",
    max: 8,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.97,
    group: "泛光",
    key: "bloomThreshold",
    label: "阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0,
    group: "泛光",
    key: "bloomRadius",
    label: "半径",
    max: 24,
    min: 0,
    step: 0.25,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.96,
    group: "泛光",
    key: "bloomSoftness",
    label: "柔化",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
] as const satisfies ParameterDefinitions

const bloomParams = [
  {
    defaultValue: 1.25,
    group: "辉光",
    key: "bloomIntensity",
    label: "强度",
    max: 8,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.6,
    group: "辉光",
    key: "bloomThreshold",
    label: "阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 6,
    group: "辉光",
    key: "bloomRadius",
    label: "半径",
    max: 24,
    min: 0,
    step: 0.25,
    type: "number",
  },
  {
    defaultValue: 0.35,
    group: "辉光",
    key: "bloomSoftness",
    label: "柔和度",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.2,
    group: "高光",
    key: "bloomKnee",
    label: "拐点",
    max: 0.5,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.5,
    group: "高光",
    key: "highlightDrive",
    label: "高光驱动",
    max: 4,
    min: 1,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const gradientParams = [
  {
    defaultValue: "custom",
    group: "控制点",
    key: "preset",
    label: "预设",
    options: [
      { label: "自定义", value: "custom" },
      { label: "森林", value: "aurora" },
      { label: "余烬", value: "sunset" },
      { label: "深渊", value: "deep-ocean" },
      { label: "紫罗兰", value: "neon-glow" },
    ],
    type: "select",
  },
  {
    defaultValue: 3,
    group: "控制点",
    key: "activePoints",
    label: "启用点数",
    max: 5,
    min: 2,
    step: 1,
    type: "number",
  },
  {
    defaultValue: "#0E0C0C",
    group: "控制点",
    key: "point1Color",
    label: "点 1 颜色",
    type: "color",
  },
  {
    defaultValue: [-0.82, -0.62] as [number, number],
    group: "控制点",
    key: "point1Position",
    label: "点 1 位置",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
  },
  {
    defaultValue: 0.42,
    group: "控制点",
    key: "point1Weight",
    label: "点 1 权重",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "#C1FF00",
    group: "控制点",
    key: "point2Color",
    label: "点 2 颜色",
    type: "color",
  },
  {
    defaultValue: [0.22, 0.72] as [number, number],
    group: "控制点",
    key: "point2Position",
    label: "点 2 位置",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
  },
  {
    defaultValue: 1.55,
    group: "控制点",
    key: "point2Weight",
    label: "点 2 权重",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "#B2DAD5",
    group: "控制点",
    key: "point3Color",
    label: "点 3 颜色",
    type: "color",
    visibleWhen: {
      gte: 3,
      key: "activePoints",
    },
  },
  {
    defaultValue: [0.88, -0.26] as [number, number],
    group: "控制点",
    key: "point3Position",
    label: "点 3 位置",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
    visibleWhen: {
      gte: 3,
      key: "activePoints",
    },
  },
  {
    defaultValue: 0.64,
    group: "控制点",
    key: "point3Weight",
    label: "点 3 权重",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      gte: 3,
      key: "activePoints",
    },
  },
  {
    defaultValue: "#3B4148",
    group: "控制点",
    key: "point4Color",
    label: "点 4 颜色",
    type: "color",
    visibleWhen: {
      gte: 4,
      key: "activePoints",
    },
  },
  {
    defaultValue: [-0.34, 0.52] as [number, number],
    group: "控制点",
    key: "point4Position",
    label: "点 4 位置",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
    visibleWhen: {
      gte: 4,
      key: "activePoints",
    },
  },
  {
    defaultValue: 0.82,
    group: "控制点",
    key: "point4Weight",
    label: "点 4 权重",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      gte: 4,
      key: "activePoints",
    },
  },
  {
    defaultValue: "#F3E7D0",
    group: "控制点",
    key: "point5Color",
    label: "点 5 颜色",
    type: "color",
    visibleWhen: {
      gte: 5,
      key: "activePoints",
    },
  },
  {
    defaultValue: [0.58, -0.76] as [number, number],
    group: "控制点",
    key: "point5Position",
    label: "点 5 位置",
    max: 1.5,
    min: -1.5,
    step: 0.01,
    type: "vec2",
    visibleWhen: {
      gte: 5,
      key: "activePoints",
    },
  },
  {
    defaultValue: 0.48,
    group: "控制点",
    key: "point5Weight",
    label: "点 5 权重",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      gte: 5,
      key: "activePoints",
    },
  },
  {
<<<<<<< HEAD
    defaultValue: "simplex",
    group: "扭曲",
=======
    defaultValue: "ridge",
    group: "扭曲",
>>>>>>> upstream/main
    key: "noiseType",
    label: "噪点类型",
    options: [
      { label: "单纯形", value: "simplex" },
      { label: "柏林", value: "perlin" },
      { label: "值噪点", value: "value" },
      { label: "泰森多边形", value: "voronoi" },
      { label: "脊状", value: "ridge" },
      { label: "湍流", value: "turbulence" },
    ],
    type: "select",
  },
  {
<<<<<<< HEAD
    defaultValue: 0,
    group: "扭曲",
=======
    defaultValue: 70.3,
    group: "扭曲",
>>>>>>> upstream/main
    key: "noiseSeed",
    label: "随机种子",
    max: 100,
    min: 0,
    step: 0.1,
    type: "number",
  },
  {
<<<<<<< HEAD
    defaultValue: 0.64,
    group: "扭曲",
=======
    defaultValue: 0.18,
    group: "扭曲",
>>>>>>> upstream/main
    key: "warpAmount",
    label: "扭曲量",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
<<<<<<< HEAD
    defaultValue: 5.56,
    group: "扭曲",
=======
    defaultValue: 2.35,
    group: "扭曲",
>>>>>>> upstream/main
    key: "warpScale",
    label: "扭曲缩放",
    max: 6,
    min: 0.1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "扭曲",
    key: "warpIterations",
    label: "迭代次数",
    max: 5,
    min: 1,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "扭曲",
    key: "warpDecay",
    label: "扭曲衰减",
    max: 3,
    min: 0.1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.5,
    group: "扭曲",
    key: "warpBias",
    label: "扭曲偏差",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.69,
    group: "扭曲",
    key: "vortexAmount",
    label: "漩涡",
    max: 1,
    min: -1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: true,
    group: "动画",
    key: "animate",
    label: "动画",
    type: "boolean",
  },
  {
<<<<<<< HEAD
    defaultValue: 0,
    group: "动画",
=======
    defaultValue: 1,
    group: "动画",
>>>>>>> upstream/main
    key: "motionAmount",
    label: "运动量",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
<<<<<<< HEAD
    defaultValue: 0.2,
    group: "动画",
=======
    defaultValue: 0.4,
    group: "动画",
>>>>>>> upstream/main
    key: "motionSpeed",
    label: "运动速度",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "animate",
    },
  },
  {
    defaultValue: 2.05,
    group: "扭曲",
    key: "falloff",
    label: "衰减",
    max: 4,
    min: 0.5,
    step: 0.01,
    type: "number",
  },
  {
<<<<<<< HEAD
    defaultValue: "reinhard",
    group: "收尾",
=======
    defaultValue: "cinematic",
    group: "后期处理",
>>>>>>> upstream/main
    key: "tonemapMode",
    label: "色调映射",
    options: [
      { label: "无", value: "none" },
      { label: "ACES", value: "aces" },
      { label: "Reinhard", value: "reinhard" },
      { label: "Toto's", value: "totos" },
      { label: "电影级", value: "cinematic" },
    ],
    type: "select",
  },
  {
    defaultValue: 0,
    group: "收尾",
    key: "glowStrength",
    label: "辉光强度",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    group: "收尾",
    key: "glowThreshold",
    label: "辉光阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.08,
    group: "收尾",
    key: "grainAmount",
    label: "颗粒",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.12,
    group: "收尾",
    key: "vignetteStrength",
    label: "暗角强度",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.5,
    group: "收尾",
    key: "vignetteRadius",
    label: "暗角半径",
    max: 1.5,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "收尾",
    key: "vignetteSoftness",
    label: "暗角柔化",
    max: 1,
    min: 0.01,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const fluidParams = [
  {
    defaultValue: 192,
    key: "simRes",
    label: "模拟分辨率",
    max: 512,
    min: 32,
    step: 32,
    type: "number",
  },
  {
    defaultValue: 1024,
    key: "dyeRes",
    label: "染料分辨率",
    max: 2048,
    min: 128,
    step: 64,
    type: "number",
  },
  {
    defaultValue: 20,
    key: "iterations",
<<<<<<< HEAD
    label: "迭代次数",
    max: 128,
    min: 4,
=======
    label: "迭代次数",
    max: 32,
    min: 1,
>>>>>>> upstream/main
    step: 1,
    type: "number",
  },
  {
<<<<<<< HEAD
    defaultValue: 0.92,
    key: "dissipation",
    label: "消散",
    max: 0.999,
    min: 0.5,
    step: 0.001,
    type: "number",
  },
  {
    defaultValue: 0.24,
    key: "pressure",
    label: "压力",
=======
    defaultValue: 4,
    key: "densityDissipation",
    label: "密度耗散",
    max: 8,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.2,
    key: "velocityDissipation",
    label: "速度耗散",
    max: 4,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    key: "pressureDissipation",
    label: "压力耗散",
>>>>>>> upstream/main
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
<<<<<<< HEAD
    defaultValue: "#3c73ff",
    key: "inkColor",
    label: "油墨颜色",
=======
    defaultValue: 30,
    key: "curlStrength",
    label: "旋度",
    max: 80,
    min: 0,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "radius",
    label: "半径",
    max: 2,
    min: 0.05,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 6000,
    key: "splatForce",
    label: "喷溅力度",
    max: 15000,
    min: 500,
    step: 100,
    type: "number",
  },
  {
    defaultValue: true,
    key: "autoSplats",
    label: "自动喷溅",
    type: "boolean",
  },
  {
    defaultValue: 1.6,
    key: "brightness",
    label: "亮度",
    max: 4,
    min: 0.1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "monochrome",
    key: "colorMode",
    label: "颜色模式",
    options: [
      { label: "单色", value: "monochrome" },
      { label: "双色调", value: "duotone" },
      { label: "源", value: "source" },
    ],
    type: "select",
  },
  {
    defaultValue: "#000000",
    key: "monoDark",
    label: "单色暗部",
>>>>>>> upstream/main
    type: "color",
    visibleWhen: { equals: "monochrome", key: "colorMode" },
  },
  {
    defaultValue: "#ffffff",
    key: "monoLight",
    label: "单色亮部",
    type: "color",
    visibleWhen: { equals: "monochrome", key: "colorMode" },
  },
  {
    defaultValue: "#101010",
    key: "duotoneDark",
    label: "双色暗部",
    type: "color",
    visibleWhen: { equals: "duotone", key: "colorMode" },
  },
  {
    defaultValue: "#f3f3ef",
    key: "duotoneLight",
    label: "双色亮部",
    type: "color",
    visibleWhen: { equals: "duotone", key: "colorMode" },
  },
] as const satisfies ParameterDefinitions

const modelParams = [
  {
    defaultValue: "studio",
    key: "environment",
    label: "环境",
    options: [
      { label: "工作室", value: "studio" },
      { label: "日落", value: "sunset" },
      { label: "仓库", value: "warehouse" },
      { label: "夜晚", value: "night" },
    ],
    type: "select",
  },
  {
    defaultValue: 1,
    key: "environmentStrength",
    label: "环境强度",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.2,
    key: "cameraDistance",
    label: "相机距离",
    max: 6,
    min: 0.2,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: [0, 0, 0] as [number, number, number],
    key: "cameraOrbit",
    label: "相机轨道",
    max: 6.283,
    min: -6.283,
    step: 0.01,
    type: "vec3",
  },
  {
    defaultValue: false,
    key: "autoRotate",
    label: "自动旋转",
    type: "boolean",
  },
  {
    defaultValue: 0.6,
    key: "autoRotateSpeed",
    label: "旋转速度",
    max: 4,
    min: -4,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const asciiParams = [
  {
    defaultValue: 12,
    key: "cellSize",
    label: "字元尺寸",
    max: 48,
    min: 4,
    step: 1,
    type: "number",
  },
  {
    animatable: false,
    defaultValue: "light",
    key: "charset",
    label: "字符集",
    options: [
      { label: "稀疏", value: "light" },
      { label: "密集", value: "dense" },
      { label: "方块", value: "blocks" },
      { label: "排线", value: "hatching" },
      { label: "二进制", value: "binary" },
      { label: "自定义", value: "custom" },
    ],
    type: "select",
  },
  {
    animatable: false,
    defaultValue: " .:-=+*#%@",
    key: "customChars",
    label: "自定义字符",
    maxLength: 32,
    type: "text",
    visibleWhen: {
      equals: "custom",
      key: "charset",
    },
  },
  {
    defaultValue: "regular",
    key: "fontWeight",
    label: "字重",
    options: [
      { label: "细体", value: "thin" },
      { label: "常规", value: "regular" },
      { label: "粗体", value: "bold" },
    ],
    type: "select",
  },
  {
    defaultValue: "monochrome",
    key: "colorMode",
    label: "颜色模式",
    options: [
      { label: "源色", value: "source" },
      { label: "单色", value: "monochrome" },
    ],
    type: "select",
  },
  {
    defaultValue: "#f5f5f0",
    key: "monoColor",
    label: "色调",
    type: "color",
    visibleWhen: {
      equals: "monochrome",
      key: "colorMode",
    },
  },
  {
    defaultValue: 0,
    key: "bgOpacity",
    label: "背景",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: "source",
      key: "colorMode",
    },
  },
  {
    defaultValue: false,
    key: "invert",
    label: "反转",
    type: "boolean",
  },
  {
    defaultValue: "none",
    group: "信号",
    key: "toneMapping",
    label: "色调映射",
    options: [
      { label: "无", value: "none" },
      { label: "ACES", value: "aces" },
      { label: "Reinhard", value: "reinhard" },
      { label: "Totos", value: "totos" },
      { label: "电影级", value: "cinematic" },
    ],
    type: "select",
  },
  {
    defaultValue: "luminance",
    group: "信号",
    key: "glyphSignalMode",
    label: "字形信号",
    options: [
      { label: "亮度", value: "luminance" },
      { label: "明度", value: "lightness" },
      { label: "红", value: "red" },
      { label: "绿", value: "green" },
      { label: "蓝", value: "blue" },
    ],
    type: "select",
  },
  {
    defaultValue: "luminance",
    group: "信号",
    key: "colorSignalMode",
    label: "颜色信号",
    options: [
      { label: "亮度", value: "luminance" },
      { label: "明度", value: "lightness" },
      { label: "红", value: "red" },
      { label: "绿", value: "green" },
      { label: "蓝", value: "blue" },
    ],
    type: "select",
  },
  {
    defaultValue: 0,
    group: "信号",
    key: "signalBlackPoint",
    label: "黑场",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "信号",
    key: "signalWhitePoint",
    label: "���场",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "信号",
    key: "signalGamma",
    label: "伽马",
    max: 5,
    min: 0.1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    group: "存在感",
    key: "presenceThreshold",
    label: "阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    group: "存在感",
    key: "presenceSoftness",
    label: "柔化",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    group: "闪烁",
    key: "shimmerAmount",
    label: "量",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "闪烁",
    key: "shimmerSpeed",
    label: "速度",
    max: 10,
    min: 0,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: 0,
    key: "directionBias",
    label: "方向偏差",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: false,
    group: "泛光",
    key: "bloomEnabled",
    label: "泛光",
    type: "boolean",
  },
  {
    defaultValue: 1.25,
    group: "泛光",
    key: "bloomIntensity",
    label: "强度",
    max: 8,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.6,
    group: "泛光",
    key: "bloomThreshold",
    label: "阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 6,
    group: "泛光",
    key: "bloomRadius",
    label: "半径",
    max: 24,
    min: 0,
    step: 0.25,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.35,
    group: "泛光",
    key: "bloomSoftness",
    label: "柔化",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
] as const satisfies ParameterDefinitions

const circuitBentParams = [
  {
    defaultValue: "source",
    key: "colorMode",
    label: "颜色模式",
    options: [
      { label: "源色", value: "source" },
      { label: "单色", value: "monochrome" },
    ],
    type: "select",
  },
  {
    defaultValue: "#ebf5ff",
    key: "monoColor",
    label: "色调",
    type: "color",
    visibleWhen: { equals: "monochrome", key: "colorMode" },
  },
  {
    defaultValue: false,
    key: "invert",
    label: "反转",
    type: "boolean",
  },
  {
    defaultValue: 0,
    group: "信号",
    key: "signalBlackPoint",
    label: "黑���",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.22,
    group: "信号",
    key: "signalWhitePoint",
    label: "白场",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 3.07,
    group: "信号",
    key: "signalGamma",
    label: "伽马",
    max: 5,
    min: 0.1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.37,
    group: "信号",
    key: "presenceThreshold",
    label: "存在感",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.64,
    group: "信号",
    key: "presenceSoftness",
    label: "存在感柔化",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 6.4,
    group: "扫描线",
    key: "linePitch",
    label: "间距",
    max: 48,
    min: 2,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: 0.5,
    group: "扫描线",
    key: "lineThickness",
    label: "粗细",
    max: 8,
    min: 0.5,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: 0,
    group: "扫描线",
    key: "lineAngle",
    label: "角度",
    max: 180,
    min: 0,
    step: 1,
    type: "number",
  },
  {
    defaultValue: "turbulence",
    group: "噪点",
    key: "noiseMode",
    label: "噪点类型",
    options: [
      { label: "正弦波", value: "sine" },
      { label: "柏林", value: "perlin" },
      { label: "湍流", value: "turbulence" },
    ],
    type: "select",
  },
  {
    defaultValue: 1,
    group: "噪点",
    key: "noiseAmount",
    label: "量",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    animatable: true,
    defaultValue: 4,
    group: "动画",
    key: "scrollSpeed",
    label: "滚动速度",
    max: 4,
    min: 0,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const patternParams = [
  {
    defaultValue: 12,
    key: "cellSize",
    label: "单元尺寸",
    max: 48,
    min: 4,
    step: 1,
    type: "number",
  },
  {
    animatable: false,
    defaultValue: "bars",
    key: "preset",
    label: "预设",
    options: [
      { label: "条纹", value: "bars" },
      { label: "烛光", value: "candles" },
      { label: "形状", value: "shapes" },
    ],
    type: "select",
  },
  {
    defaultValue: "source",
    key: "colorMode",
    label: "颜色模式",
    options: [
      { label: "源色", value: "source" },
      { label: "量化", value: "quantized" },
      { label: "单色", value: "monochrome" },
      { label: "自定义", value: "custom" },
    ],
    type: "select",
  },
  {
    defaultValue: "#f5f5f0",
    key: "monoColor",
    label: "色调",
    type: "color",
    visibleWhen: {
      equals: "monochrome",
      key: "colorMode",
    },
  },
  {
    defaultValue: 0,
    key: "bgOpacity",
    label: "背景",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: "source",
      key: "colorMode",
    },
  },
  {
    defaultValue: false,
    key: "invert",
    label: "反转",
    type: "boolean",
  },
  {
    defaultValue: 4,
    description: "调色板在亮度带间均匀分布。",
    key: "customColorCount",
    label: "颜色数量",
    max: 4,
    min: 2,
    step: 1,
    type: "number",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: 0,
    description: "将调色板映射偏向暗部或亮部。",
    key: "customLuminanceBias",
    label: "亮度偏差",
    max: 1,
    min: -1,
    step: 0.01,
    type: "number",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: "#F5F5F0",
    key: "customBgColor",
    label: "背景",
    type: "color",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: "#0d1014",
    key: "customColor1",
    label: "暗部",
    type: "color",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: "#4d5057",
    key: "customColor2",
    label: "中间调 / 亮部",
    type: "color",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: "#969aa2",
    key: "customColor3",
    label: "高中调",
    type: "color",
    visibleWhen: {
      gte: 3,
      key: "customColorCount",
    },
  },
  {
    defaultValue: "#e1e2de",
    key: "customColor4",
    label: "高光",
    type: "color",
    visibleWhen: {
      gte: 4,
      key: "customColorCount",
    },
  },
  {
    defaultValue: false,
    group: "泛光",
    key: "bloomEnabled",
    label: "泛光",
    type: "boolean",
  },
  {
    defaultValue: 1.25,
    group: "泛光",
    key: "bloomIntensity",
    label: "强度",
    max: 8,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.6,
    group: "泛光",
    key: "bloomThreshold",
    label: "阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 6,
    group: "泛光",
    key: "bloomRadius",
    label: "半径",
    max: 24,
    min: 0,
    step: 0.25,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.35,
    group: "泛光",
    key: "bloomSoftness",
    label: "柔化",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
] as const satisfies ParameterDefinitions

const ditheringParams = [
  {
    defaultValue: "custom",
    group: "图案",
    key: "preset",
    label: "预设",
    options: [
      { label: "自定义", value: "custom" },
      { label: "Game Boy", value: "gameboy" },
    ],
    type: "select",
  },
  {
    defaultValue: "bayer-4x4",
    group: "图案",
    key: "algorithm",
    label: "算法",
    options: [
      { label: "Bayer 2x2", value: "bayer-2x2" },
      { label: "Bayer 4x4", value: "bayer-4x4" },
      { label: "Bayer 8x8", value: "bayer-8x8" },
      { label: "噪点", value: "noise" },
    ],
    type: "select",
  },
  {
    defaultValue: "source",
    group: "颜色",
    key: "colorMode",
    label: "颜色模式",
    options: [
      { label: "单色", value: "monochrome" },
      { label: "源色", value: "source" },
      { label: "双色调", value: "duo-tone" },
    ],
    type: "select",
  },
  {
    defaultValue: "#f5f5f0",
    group: "颜色",
    key: "monoColor",
    label: "颜色",
    type: "color",
    visibleWhen: {
      equals: "monochrome",
      key: "colorMode",
    },
  },
  {
    defaultValue: "#101010",
    group: "颜色",
    key: "shadowColor",
    label: "暗部",
    type: "color",
    visibleWhen: {
      equals: "duo-tone",
      key: "colorMode",
    },
  },
  {
    defaultValue: "#f5f2e8",
    group: "颜色",
    key: "highlightColor",
    label: "高光",
    type: "color",
    visibleWhen: {
      equals: "duo-tone",
      key: "colorMode",
    },
  },
  {
    defaultValue: 1,
    group: "图案",
    key: "pixelSize",
    label: "像素尺寸",
    max: 24,
    min: 1,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 0.5,
    group: "图案",
    key: "spread",
    label: "强度",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 4,
    group: "颜色",
    key: "levels",
    label: "色阶数",
    max: 16,
    min: 2,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "效果",
    key: "dotScale",
    label: "点缩放",
    max: 1,
    min: 0.1,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: false,
    group: "效果",
    key: "animateDither",
    label: "抖动动画",
    type: "boolean",
  },
  {
    defaultValue: 1,
    group: "效果",
    key: "ditherSpeed",
    label: "抖动速度",
    max: 3,
    min: 0,
    step: 0.5,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "animateDither",
    },
  },
  {
    defaultValue: false,
    group: "效果",
    key: "chromaticSplit",
    label: "色差分离",
    type: "boolean",
  },
] as const satisfies ParameterDefinitions

const halftoneParams = [
  {
    defaultValue: "cmyk",
    key: "colorMode",
    label: "颜色模式",
    options: [
      { label: "源色", value: "source" },
      { label: "单色", value: "monochrome" },
      { label: "双色调", value: "duotone" },
      { label: "自定义", value: "custom" },
      { label: "CMYK", value: "cmyk" },
    ],
    type: "select",
  },
  {
    defaultValue: "circle",
    key: "shape",
    label: "形状",
    options: [
      { label: "圆形", value: "circle" },
      { label: "方形", value: "square" },
      { label: "菱形", value: "diamond" },
      { label: "线条", value: "line" },
    ],
    type: "select",
  },
  {
    defaultValue: 5,
    key: "spacing",
    label: "间距",
    max: 48,
    min: 2,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "dotSize",
    label: "网点尺寸",
    max: 3,
    min: 0.1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    key: "dotMin",
    label: "网点最小值",
    max: 0.5,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 28,
    key: "angle",
    label: "角度",
    max: 360,
    min: 0,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "contrast",
    label: "对比度",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.25,
    key: "softness",
    label: "柔化",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    key: "dotGain",
    label: "网点扩张",
    description: "模拟墨水渗入纸张纤维",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    key: "dotMorph",
    label: "网点变形",
    description: "根据色调值混合网点形状（中调由圆变方）",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: false,
    key: "invertLuma",
    label: "反转",
    type: "boolean",
  },
  {
    defaultValue: 4,
    description: "调色板在亮度带间均匀分布。",
    key: "customColorCount",
    label: "颜色数量",
    max: 4,
    min: 2,
    step: 1,
    type: "number",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: 0,
    description: "将调色板映射偏向暗部或亮部。",
    key: "customLuminanceBias",
    label: "亮度偏差",
    max: 1,
    min: -1,
    step: 0.01,
    type: "number",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: false,
    group: "泛光",
    key: "bloomEnabled",
    label: "泛光",
    type: "boolean",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: 1.25,
    group: "泛光",
    key: "bloomIntensity",
    label: "强度",
    max: 8,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: { equals: true, key: "bloomEnabled" },
  },
  {
    defaultValue: 0.6,
    group: "泛光",
    key: "bloomThreshold",
    label: "阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: { equals: true, key: "bloomEnabled" },
  },
  {
    defaultValue: 6,
    group: "泛光",
    key: "bloomRadius",
    label: "半径",
    max: 24,
    min: 0,
    step: 0.25,
    type: "number",
    visibleWhen: { equals: true, key: "bloomEnabled" },
  },
  {
    defaultValue: 0.35,
    group: "泛光",
    key: "bloomSoftness",
    label: "柔化",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: { equals: true, key: "bloomEnabled" },
  },
  {
    defaultValue: "#F5F5F0",
    key: "customBgColor",
    label: "背景",
    type: "color",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: "#0d1014",
    key: "customColor1",
    label: "暗部",
    type: "color",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: "#4d5057",
    key: "customColor2",
    label: "中间调 / 亮部",
    type: "color",
    visibleWhen: { equals: "custom", key: "colorMode" },
  },
  {
    defaultValue: "#969aa2",
    key: "customColor3",
    label: "高中调",
    type: "color",
    visibleWhen: {
      gte: 3,
      key: "customColorCount",
    },
  },
  {
    defaultValue: "#e1e2de",
    key: "customColor4",
    label: "高光",
    type: "color",
    visibleWhen: {
      gte: 4,
      key: "customColorCount",
    },
  },
  {
    defaultValue: "#0d1014",
    key: "ink",
    label: "油墨",
    type: "color",
    visibleWhen: { equals: "monochrome", key: "colorMode" },
  },
  {
    defaultValue: "#F5F5F0",
    key: "duotoneLight",
    label: "亮色",
    type: "color",
    visibleWhen: { equals: "duotone", key: "colorMode" },
  },
  {
    defaultValue: "#1d1d1c",
    key: "duotoneDark",
    label: "暗色",
    type: "color",
    visibleWhen: { equals: "duotone", key: "colorMode" },
  },
  {
    defaultValue: "process",
    key: "preset",
    label: "油墨预设",
    options: [
      { label: "标准 CMYK", value: "process" },
      { label: "孔版印刷", value: "risograph" },
      { label: "报纸印刷", value: "newspaper" },
      { label: "复古", value: "vintage" },
      { label: "自定义", value: "custom" },
    ],
    type: "select",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 0.5,
    key: "gcr",
    label: "黑版生成",
    description: "控制 K 版与 C+M+Y 的比例",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: "subtractive",
    key: "cmykBlend",
    label: "CMYK 混合",
    options: [
      { label: "减色", value: "subtractive" },
      { label: "叠印", value: "overprint" },
    ],
    type: "select",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 15,
    key: "cyanAngle",
    label: "青版角度",
    max: 90,
    min: 0,
    step: 1,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 75,
    key: "magentaAngle",
    label: "品版角度",
    max: 90,
    min: 0,
    step: 1,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 0,
    key: "yellowAngle",
    label: "黄版角度",
    max: 90,
    min: 0,
    step: 1,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 45,
    key: "keyAngle",
    label: "黑版角度",
    max: 90,
    min: 0,
    step: 1,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: "#F5F5F0",
    key: "paperColor",
    label: "纸张颜色",
    type: "color",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 0.15,
    key: "paperGrain",
    label: "纸张颗粒",
    max: 0.5,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: 0,
    key: "registration",
    label: "套版误差",
    description: "模拟 CMYK 印刷版位偏移",
    max: 5,
    min: 0,
    step: 0.1,
    type: "number",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: "#00AEEF",
    key: "inkCyan",
    label: "青色墨",
    type: "color",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: "#EC008C",
    key: "inkMagenta",
    label: "品红墨",
    type: "color",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: "#FFF200",
    key: "inkYellow",
    label: "黄色墨",
    type: "color",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
  {
    defaultValue: "#1a1a1a",
    key: "inkKey",
    label: "黑色墨",
    type: "color",
    visibleWhen: { equals: "cmyk", key: "colorMode" },
  },
] as const satisfies ParameterDefinitions

const particleGridParams = [
  {
    defaultValue: "256",
    key: "gridResolution",
<<<<<<< HEAD
    label: "分辨率",
    max: 512,
    min: 32,
    step: 4,
    type: "number",
=======
    label: "分辨率",
    options: [
      { label: "32", value: "32" },
      { label: "64", value: "64" },
      { label: "128", value: "128" },
      { label: "256", value: "256" },
      { label: "512", value: "512" },
      { label: "1024", value: "1024" },
      { label: "2048", value: "2048" },
      { label: "4096", value: "4096" },
    ],
    type: "select",
>>>>>>> upstream/main
  },
  {
    defaultValue: 4,
    key: "pointSize",
    label: "粒子尺寸",
    max: 32,
    min: 1,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 0.1,
    key: "displacement",
    label: "位移",
    max: 2,
    min: -2,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "#000000",
    key: "backgroundColor",
    label: "背景",
    type: "color",
  },
  {
    defaultValue: 0,
    group: "运动",
    key: "noiseAmount",
    label: "量",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 3,
    group: "运动",
    key: "noiseScale",
    label: "缩放",
    max: 10,
    min: 0.5,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: 0.5,
    group: "运动",
    key: "noiseSpeed",
    label: "速度",
    max: 3,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: false,
    group: "泛光",
    key: "bloomEnabled",
    label: "泛光",
    type: "boolean",
  },
  {
    defaultValue: 1.25,
    group: "泛光",
    key: "bloomIntensity",
    label: "强度",
    max: 8,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.6,
    group: "泛光",
    key: "bloomThreshold",
    label: "阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 6,
    group: "泛光",
    key: "bloomRadius",
    label: "半径",
    max: 24,
    min: 0,
    step: 0.25,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.35,
    group: "泛光",
    key: "bloomSoftness",
    label: "柔化",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
] as const satisfies ParameterDefinitions

const pixelationParams = [
  {
    defaultValue: 8,
    key: "cellSize",
    label: "像素尺寸",
    max: 64,
    min: 2,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "aspectRatio",
    label: "长宽比",
    max: 4,
    min: 0.25,
    step: 0.05,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const pixelTrailParams = [
  {
    defaultValue: 24,
    key: "cellSize",
    label: "单元格大小",
    max: 128,
    min: 4,
    step: 1,
    type: "number",
    unit: "px",
  },
  {
    defaultValue: 0.04,
    key: "radius",
    label: "半径",
    max: 0.3,
    min: 0.005,
    step: 0.005,
    type: "number",
  },
  {
    defaultValue: 0.9,
    key: "decay",
    label: "衰减",
    max: 0.999,
    min: 0.5,
    step: 0.001,
    type: "number",
  },
  {
    defaultValue: 0.02,
    key: "displaceAmount",
    label: "位移",
    max: 0.2,
    min: 0,
    step: 0.001,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "intensity",
    label: "强度",
    max: 2,
    min: 0,
    step: 0.05,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const magnifyLensParams = [
  {
    defaultValue: 0.18,
    key: "radius",
    label: "半径",
    max: 0.5,
    min: 0.02,
    step: 0.005,
    type: "number",
  },
  {
    defaultValue: 0.4,
    key: "softness",
    label: "柔和度",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.8,
    key: "zoom",
    label: "缩放",
    max: 4,
    min: 1,
    step: 0.05,
    type: "number",
  },
  {
    defaultValue: 0.012,
    key: "chromaStrength",
    label: "色散边缘",
    max: 0.05,
    min: 0,
    step: 0.001,
    type: "number",
  },
  {
    defaultValue: 0.2,
    key: "followLag",
    label: "跟随延迟",
    max: 0.95,
    min: 0,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const directionalBlurParams = [
  {
    defaultValue: "linear",
    key: "mode",
    label: "模式",
    options: [
      { label: "线性", value: "linear" },
      { label: "径向", value: "radial" },
    ],
    type: "select",
  },
  {
    defaultValue: 18,
    key: "strength",
    label: "强度",
    max: 96,
    min: 0,
    step: 0.5,
    type: "number",
    unit: "px",
  },
  {
    defaultValue: 8,
    key: "samples",
    label: "采样数",
    max: 16,
    min: 1,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 0,
    key: "angle",
    label: "角度",
    max: 360,
    min: 0,
    step: 1,
    type: "number",
    unit: "°",
    visibleWhen: { key: "mode", equals: "linear" },
  },
  {
    defaultValue: [0.5, 0.5] as [number, number],
    key: "center",
    label: "中心",
    max: 1,
    min: 0,
    step: 0.01,
    type: "vec2",
    visibleWhen: { key: "mode", equals: "radial" },
  },
] as const satisfies ParameterDefinitions

const pixelSortingParams = [
  {
    defaultValue: 0.25,
    key: "threshold",
    label: "阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "upperThreshold",
    label: "上限阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "horizontal",
    key: "direction",
    label: "方向",
    options: [
      { label: "水平", value: "horizontal" },
      { label: "垂直", value: "vertical" },
    ],
    type: "select",
  },
  {
    defaultValue: "luma",
    key: "mode",
    label: "模式",
    options: [
      { label: "亮度", value: "luma" },
      { label: "色相", value: "hue" },
      { label: "饱和度", value: "saturation" },
    ],
    type: "select",
  },
  {
    defaultValue: false,
    key: "reverse",
    label: "反向",
    type: "boolean",
  },
  {
    defaultValue: 0.3,
    key: "range",
    label: "范围",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const voxelParams = [
  {
    defaultValue: 24,
    key: "cellSize",
    label: "单元格大小",
    max: 96,
    min: 4,
    step: 1,
    type: "number",
    unit: "px",
  },
  {
    defaultValue: 0,
    key: "depth",
    label: "深度",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 6,
    key: "maxHeight",
    label: "最大高度",
    max: 8,
    min: 1,
    step: 1,
    type: "number",
    visibleWhen: { gte: 0.01, key: "depth" },
  },
  {
    defaultValue: 1,
    key: "topShade",
    label: "顶部明暗",
    max: 1.5,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.78,
    key: "lightShade",
    label: "亮面",
    max: 1.5,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.55,
    key: "darkShade",
    label: "暗面",
    max: 1.5,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: false,
    key: "flipLight",
    label: "翻转光照",
    type: "boolean",
  },
  {
    defaultValue: false,
    key: "lego",
    label: "Lego",
    type: "boolean",
  },
  {
    defaultValue: 1.0,
    key: "outlineWidth",
    label: "描边",
    max: 4,
    min: 0,
    step: 0.1,
    type: "number",
    unit: "px",
  },
  {
    defaultValue: "#0a0a0a",
    key: "outlineColor",
    label: "描边颜色",
    type: "color",
  },
] as const satisfies ParameterDefinitions

const posterizeParams = [
  {
    defaultValue: 5,
    key: "levels",
    label: "色阶数",
    max: 16,
    min: 2,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "gamma",
    label: "伽马",
    max: 2.5,
    min: 0.4,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "rgb",
    key: "mode",
    label: "模式",
    options: [
      { label: "RGB", value: "rgb" },
      { label: "亮度", value: "luma" },
    ],
    type: "select",
  },
] as const satisfies ParameterDefinitions

const thresholdParams = [
  {
    defaultValue: 0.5,
    key: "threshold",
    label: "阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.02,
    key: "softness",
    label: "柔化",
    max: 0.2,
    min: 0,
    step: 0.001,
    type: "number",
  },
  {
    defaultValue: 0.08,
    key: "noise",
    label: "噪点",
    max: 0.3,
    min: 0,
    step: 0.001,
    type: "number",
  },
  {
    defaultValue: false,
    key: "invert",
    label: "反转",
    type: "boolean",
  },
] as const satisfies ParameterDefinitions

const smearParams = [
  {
    defaultValue: 0,
    key: "angle",
    label: "角度",
    max: 360,
    min: 0,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 0.25,
    key: "start",
    label: "起点",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.75,
    key: "end",
    label: "终点",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 24,
    key: "strength",
    label: "强度",
    max: 64,
    min: 0,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 12,
    key: "samples",
    label: "采样数",
    max: 32,
    min: 4,
    step: 1,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const flutedGlassParams = [
  {
    defaultValue: "architectural",
    key: "preset",
    label: "预设",
    options: [
      { label: "建筑", value: "architectural" },
      { label: "绘画", value: "painterly" },
    ],
    type: "select",
  },
  {
    defaultValue: 20,
    key: "frequency",
    label: "频率",
    max: 100,
    min: 2,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 0.02,
    key: "amplitude",
    label: "振幅",
    max: 0.1,
    min: 0,
    step: 0.001,
    type: "number",
  },
  {
    defaultValue: 0.28,
    key: "warp",
    label: "扭曲",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.35,
    key: "irregularity",
    label: "不规则度",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0,
    key: "angle",
    label: "角度",
    max: 360,
    min: 0,
    step: 1,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const plotterParams = [
  {
    defaultValue: "ink",
    key: "colorMode",
    label: "颜色",
    options: [
      { label: "油墨", value: "ink" },
      { label: "源色", value: "source" },
    ],
    type: "select",
  },
  {
    defaultValue: 12,
    key: "gap",
    label: "间距",
    max: 120,
    min: 10,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 1.5,
    key: "weight",
    label: "线重",
    max: 5,
    min: 0.5,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: 90,
    key: "angle",
    label: "角度",
    max: 180,
    min: 0,
    step: 1,
    type: "number",
  },
  {
    defaultValue: true,
    key: "crosshatch",
    label: "交叉排线",
    type: "boolean",
  },
  {
    defaultValue: 135,
    key: "crossAngle",
    label: "交叉角度",
    max: 180,
    min: 0,
    step: 1,
    type: "number",
    visibleWhen: { key: "crosshatch", equals: true },
  },
  {
    defaultValue: 0.5,
    key: "threshold",
    label: "阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.3,
    key: "wobble",
    label: "抖动",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "#f5f0e8",
    key: "paperColor",
    label: "纸张颜色",
    type: "color",
  },
  {
    defaultValue: "#1a1a1a",
    key: "inkColor",
    label: "油墨颜色",
    type: "color",
    visibleWhen: { key: "colorMode", equals: "ink" },
  },
] as const satisfies ParameterDefinitions

const crtParams = [
  {
    defaultValue: "slot-mask",
    key: "crtMode",
    label: "模式",
    options: [
      { label: "荫罩显示器", value: "slot-mask" },
      { label: "孔栅显示器", value: "aperture-grille" },
      { label: "复合电视", value: "composite-tv" },
    ],
    type: "select",
  },
  {
    defaultValue: 3,
    key: "cellSize",
    label: "掩膜缩放",
    max: 32,
    min: 3,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 0.17,
    key: "scanlineIntensity",
    label: "扫描线强度",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "maskIntensity",
    label: "掩膜强度",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.15,
    group: "失真",
    key: "barrelDistortion",
    label: "桶形失真",
    max: 0.3,
    min: 0,
    step: 0.001,
    type: "number",
  },
  {
    defaultValue: 2,
    group: "失真",
    key: "chromaticAberration",
    label: "色散",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.58,
    group: "荧光体",
    key: "beamFocus",
    label: "电子束聚焦",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.2,
    group: "荧光体",
    key: "brightness",
    label: "亮度",
    max: 100,
    min: 0.5,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    group: "荧光体",
    key: "highlightDrive",
    label: "高光驱动",
    max: 100,
    min: 1,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.62,
    group: "荧光体",
    key: "highlightThreshold",
    label: "高光阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.25,
    group: "荧光体",
    key: "shoulder",
    label: "肩部曲线",
    max: 4,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1.15,
    group: "荧光体",
    key: "chromaRetention",
    label: "色度保留",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.16,
    group: "荧光体",
    key: "shadowLift",
    label: "暗部提升",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.18,
    group: "荧光体",
    key: "persistence",
    label: "余辉",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.45,
    group: "失真",
    key: "vignetteIntensity",
    label: "暗角",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.2,
    group: "噪声",
    key: "flickerIntensity",
    label: "闪烁",
    max: 0.2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.13,
    group: "噪声",
    key: "glitchIntensity",
    label: "故障",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 5,
    group: "噪声",
    key: "glitchSpeed",
    label: "故障速度",
    max: 5,
    min: 0.1,
    step: 0.1,
    type: "number",
    visibleWhen: {
      gte: 0.01,
      key: "glitchIntensity",
    },
  },
  {
    defaultValue: 0.45,
    group: "信号",
    key: "signalArtifacts",
    label: "信号干扰",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: "composite-tv",
      key: "crtMode",
    },
  },
  {
    defaultValue: true,
    group: "泛光",
    key: "bloomEnabled",
    label: "泛光",
    type: "boolean",
  },
  {
    defaultValue: 1.93,
    group: "泛光",
    key: "bloomIntensity",
    label: "强度",
    max: 8,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0,
    group: "泛光",
    key: "bloomThreshold",
    label: "阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 8,
    group: "泛光",
    key: "bloomRadius",
    label: "半径",
    max: 24,
    min: 0,
    step: 0.25,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
  {
    defaultValue: 0.31,
    group: "泛光",
    key: "bloomSoftness",
    label: "柔化",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
    visibleWhen: {
      equals: true,
      key: "bloomEnabled",
    },
  },
] as const satisfies ParameterDefinitions

const edgeDetectParams = [
  {
    defaultValue: 0.1,
    key: "threshold",
    label: "阈值",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 1,
    key: "strength",
    label: "强度",
    max: 5,
    min: 0.1,
    step: 0.1,
    type: "number",
  },
  {
    defaultValue: false,
    key: "invert",
    label: "反转",
    type: "boolean",
  },
  {
    defaultValue: "overlay",
    key: "colorMode",
    label: "颜色",
    options: [
      { label: "叠加", value: "overlay" },
      { label: "单色", value: "mono" },
      { label: "源色", value: "source" },
    ],
    type: "select",
  },
  {
    defaultValue: "#ffffff",
    key: "lineColor",
    label: "线条颜色",
    type: "color",
    visibleWhen: { key: "colorMode", equals: "mono" },
  },
  {
    defaultValue: "#000000",
    key: "bgColor",
    label: "背景",
    type: "color",
    visibleWhen: { key: "colorMode", equals: "mono" },
  },
] as const satisfies ParameterDefinitions

const displacementMapParams = [
  {
    defaultValue: 20,
    key: "strength",
    label: "强度",
    max: 200,
    min: 0,
    step: 1,
    type: "number",
    unit: "px",
  },
  {
    defaultValue: "both",
    key: "direction",
    label: "方向",
    options: [
      { label: "双向", value: "both" },
      { label: "水平", value: "horizontal" },
      { label: "垂直", value: "vertical" },
    ],
    type: "select",
  },
  {
    defaultValue: "luminance",
    key: "channel",
    label: "通道",
    options: [
      { label: "亮度", value: "luminance" },
      { label: "红", value: "red" },
      { label: "绿", value: "green" },
      { label: "蓝", value: "blue" },
    ],
    type: "select",
  },
  {
    defaultValue: 0.5,
    key: "midpoint",
    label: "中间点",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const chromaticAberrationParams = [
  {
    defaultValue: 5,
    key: "intensity",
    label: "强度",
    max: 50,
    min: 0,
    step: 0.5,
    type: "number",
    unit: "px",
  },
  {
    defaultValue: "radial",
    key: "direction",
    label: "方向",
    options: [
      { label: "径向", value: "radial" },
      { label: "水平", value: "horizontal" },
      { label: "垂直", value: "vertical" },
    ],
    type: "select",
  },
  {
    defaultValue: [0.5, 0.5],
    key: "center",
    label: "中心",
    max: 1,
    min: 0,
    step: 0.01,
    type: "vec2",
    visibleWhen: { key: "direction", equals: "radial" },
  },
  {
    defaultValue: 0,
    key: "angle",
    label: "角度",
    max: 360,
    min: 0,
    step: 1,
    type: "number",
    unit: "°",
    visibleWhen: { key: "direction", equals: "horizontal" },
  },
] as const satisfies ParameterDefinitions

const blurParams = [
  {
    defaultValue: 8,
    key: "radius",
    label: "半径",
    max: 64,
    min: 0,
    step: 1,
    type: "number",
  },
  {
    defaultValue: 2,
    key: "passes",
    label: "次数",
    max: 8,
    min: 1,
    step: 1,
    type: "number",
  },
] as const satisfies ParameterDefinitions

const sliceParams = [
  {
    defaultValue: 180,
    key: "amount",
    label: "量",
    max: 480,
    min: 0,
    step: 1,
    type: "number",
    unit: "px",
  },
  {
    defaultValue: 28,
    key: "sliceHeight",
    label: "切片高度",
    max: 240,
    min: 2,
    step: 1,
    type: "number",
    unit: "px",
  },
  {
    defaultValue: 120,
    key: "blockWidth",
    label: "块宽度",
    max: 640,
    min: 8,
    step: 1,
    type: "number",
    unit: "px",
  },
  {
    defaultValue: 0.58,
    key: "density",
    label: "密度",
    max: 1,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.18,
    key: "dispersion",
    label: "弥散",
    max: 0.5,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: 0.2,
    key: "speed",
    label: "速度",
    max: 2,
    min: 0,
    step: 0.01,
    type: "number",
  },
  {
    defaultValue: "right",
    key: "direction",
    label: "方向",
    options: [
      { label: "向右", value: "right" },
      { label: "向左", value: "left" },
      { label: "双向", value: "both" },
    ],
    type: "select",
  },
] as const satisfies ParameterDefinitions

const layerDefinitions: Record<LayerType, LayerDefinition> = {
  ascii: {
    defaultName: "ASCII 字符",
    kind: "effect",
    params: asciiParams,
    type: "ascii",
  },
  bloom: {
    defaultName: "Bloom",
    kind: "effect",
    params: bloomParams,
    type: "bloom",
  },
  "circuit-bent": {
    defaultName: "电路弯曲",
    kind: "effect",
    params: circuitBentParams,
    type: "circuit-bent",
  },
  "directional-blur": {
    defaultName: "方向模糊",
    kind: "effect",
    params: directionalBlurParams,
    type: "directional-blur",
  },
  blur: {
    defaultName: "模糊",
    kind: "effect",
    params: blurParams,
    type: "blur",
  },
  crt: {
    defaultName: "CRT 显示器",
    kind: "effect",
    params: crtParams,
    type: "crt",
  },
  dithering: {
    defaultName: "抖动",
    kind: "effect",
    params: ditheringParams,
    type: "dithering",
  },
  fluid: {
    defaultName: "流体",
    kind: "source",
    params: fluidParams,
    type: "fluid",
  },
  gradient: {
    defaultName: "渐变",
    kind: "source",
    params: gradientParams,
    type: "gradient",
  },
  ink: {
    defaultName: "墨水",
    kind: "effect",
    params: inkParams,
    type: "ink",
  },
  text: {
    defaultName: "文字",
    kind: "source",
    params: textParams,
    type: "text",
  },
  "custom-shader": {
    defaultName: "自定义着色器",
    kind: "source",
    params: customShaderParams,
    type: "custom-shader",
  },
  halftone: {
    defaultName: "半色调",
    kind: "effect",
    params: halftoneParams,
    type: "halftone",
  },
  pattern: {
    defaultName: "图案",
    kind: "effect",
    params: patternParams,
    type: "pattern",
  },
  "particle-grid": {
    defaultName: "粒子网格",
    kind: "effect",
    params: particleGridParams,
    type: "particle-grid",
  },
  posterize: {
    defaultName: "色调分离",
    kind: "effect",
    params: posterizeParams,
    type: "posterize",
  },
  threshold: {
    defaultName: "阈值",
    kind: "effect",
    params: thresholdParams,
    type: "threshold",
  },
  smear: {
    defaultName: "渐进模糊",
    kind: "effect",
    params: smearParams,
    type: "smear",
  },
  "fluted-glass": {
    defaultName: "条纹玻璃",
    kind: "effect",
    params: flutedGlassParams,
    type: "fluted-glass",
  },
  plotter: {
    defaultName: "绘图仪",
    kind: "effect",
    params: plotterParams,
    type: "plotter",
  },
  image: {
    assetKind: "image",
    defaultName: "图片",
    kind: "source",
    params: imageParams,
    type: "image",
  },
  live: {
    defaultName: "实时摄像头",
    kind: "source",
    params: liveParams,
    type: "live",
  },
  model: {
    assetKind: "model",
    defaultName: "3D 模型",
    kind: "model",
    params: modelParams,
    type: "model",
  },
  "pixel-sorting": {
    defaultName: "像素排序",
    kind: "effect",
    params: pixelSortingParams,
    type: "pixel-sorting",
  },
  pixelation: {
    defaultName: "像素化",
    kind: "effect",
    params: pixelationParams,
    type: "pixelation",
  },
  slice: {
    defaultName: "切片",
    kind: "effect",
    params: sliceParams,
    type: "slice",
  },
  video: {
    assetKind: "video",
    defaultName: "视频",
    kind: "source",
    params: videoParams,
    type: "video",
  },
  "edge-detect": {
    defaultName: "边缘检测",
    kind: "effect",
    params: edgeDetectParams,
    type: "edge-detect",
  },
  "displacement-map": {
    defaultName: "置换贴图",
    kind: "effect",
    params: displacementMapParams,
    type: "displacement-map",
  },
  "chromatic-aberration": {
    defaultName: "色差",
    kind: "effect",
    params: chromaticAberrationParams,
    type: "chromatic-aberration",
  },
  "pixel-trail": {
    defaultName: "Pixel Trail",
    kind: "source",
    params: pixelTrailParams,
    type: "pixel-trail",
  },
  "magnify-lens": {
    defaultName: "Magnify Lens",
    kind: "source",
    params: magnifyLensParams,
    type: "magnify-lens",
  },
  voxel: {
    defaultName: "Voxel",
    kind: "effect",
    params: voxelParams,
    type: "voxel",
  },
}

export const DEFAULT_SOURCE_LAYER_TYPE: SourceLayerType = "gradient"
export const DEFAULT_EFFECT_LAYER_TYPE: EffectLayerType = "ascii"
export const DEFAULT_MODEL_LAYER_TYPE: ModelLayerType = "model"

export function getLayerDefinition(type: LayerType): LayerDefinition {
  return layerDefinitions[type]
}

export function getLayerDefinitions(): LayerDefinition[] {
  return Object.values(layerDefinitions)
}

export function getLayerDefinitionsByKind(kind: LayerKind): LayerDefinition[] {
  return getLayerDefinitions().filter((definition) => definition.kind === kind)
}
